### ISSUE TITLE
MACOS won't let it open

### ISSUE THREAD

**Issue by jbschreiber** [katherinemwood/corvids#4]
HI,
I downloaded the standalone and it won't let it open.  MAC OS Catalina. Getting the "cannot be verified as not containing malware." Looking for suggestions of a workaround. Thanks.

**Comment by sean-wilner** [comment]
Hi,

This is because we are not on the Mac App store. The MacOS Gatekeeper is warning you that Apple hasn't verified our software. To get around this, please follow these instructions:

`How to override the “macOS cannot verify that this app is free from malware” warning – Guide
Only follow the next steps if you are a hundred percent certain that the app you are trying to install is safe:

Open Finder and find the application that gives you the “macOS cannot verify that this app is free from malware” warning message.
Control-Click on the application.
Access the shortcut menu and click Open. After you do this, the app will be whitelisted and you will be able to open it from now on without getting the “macOS cannot verify that this app is free from malware” warning.
Another way to whitelist an app is to click the Open Anyway available in Security & Privacy Preferences. Note that this button would only be available for an hour after you try to open a blocked app. To reach this button, open the Apple Menu, go to System Preferences, click on Security & Privacy, and select General.
This short guide should help you install and freely use apps that are not trusted by Apple because they are not in the App Store but, as we said, you should be careful with such apps and only run them if you are certain that they are not dangerous.`
